Curtis
Jonatch/Team4_Project pull request #72
Opened 2023-04-28 03:55 UTC by MyrtleTurtle22

html where Users can select completed courses for several majors

2023-04-28 15:11 UTC, phil-keita approved these changes

2023-05-01 18:49 UTC, phil-keita approved these changes

2023-05-01 18:55 UTC, Jonatch approved these changes

2023-05-01 18:57 UTC, Jonatch requested changes
We need to make a couple changes

2023-05-01 18:58 UTC, closed without merging